<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Bin;

class BinSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        // Bin::factory()->count(50)->hasPosts(1)->create();

        $bins = [
            [
                'skim' => 'PHKT03',
                'jenispremis' => 'RUMAH KAMPUNG',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'PEMILIK',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 120L',
                'jumlahtong' => '1',
                'nosiritong' => 'A2041531',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
            [
                'skim' => 'PHKT03',
                'jenispremis' => 'RUMAH KAMPUNG',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'PEMILIK',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 120L',
                'jumlahtong' => '1',
                'nosiritong' => 'A2041531',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
            [
                'skim' => 'PHKT03',
                'jenispremis' => 'RUMAH KAMPUNG',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'PEMILIK',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 120L',
                'jumlahtong' => '1',
                'nosiritong' => 'A2041531',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
            [
                'skim' => 'PHKT03',
                'jenispremis' => 'RUMAH KAMPUNG',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'PEMILIK',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 120L',
                'jumlahtong' => '1',
                'nosiritong' => 'A2041531',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
            [
                'skim' => 'PHKT03',
                'jenispremis' => 'RUMAH KAMPUNG',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'PEMILIK',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 120L',
                'jumlahtong' => '1',
                'nosiritong' => 'A2041531',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
            [
                'skim' => 'PHKT02',
                'jenispremis' => 'RUMAH KAMPUNG',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'PEMILIK',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 120L',
                'jumlahtong' => '1',
                'nosiritong' => 'A2041531',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
            [
                'skim' => 'PHKT02',
                'jenispremis' => 'RUMAH KAMPUNG',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'PEMILIK',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 120L',
                'jumlahtong' => '1',
                'nosiritong' => 'A2041531',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
            [
                'skim' => 'PHKT01',
                'jenispremis' => 'RUMAH KAMPUNG',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'PEMILIK',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 120L',
                'jumlahtong' => '1',
                'nosiritong' => 'A2041531',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
            [
                'skim' => 'PHKT03',
                'jenispremis' => 'KEDAI',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'PEMILIK',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 120L',
                'jumlahtong' => '1',
                'nosiritong' => 'A2041531',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
            [
                'skim' => 'PHKT03',
                'jenispremis' => 'KEDAI',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'PEMILIK',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 120L',
                'jumlahtong' => '1',
                'nosiritong' => 'A2041531',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
            [
                'skim' => 'PHKT01',
                'jenispremis' => 'RUMAH',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'PEMILIK',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 120L',
                'jumlahtong' => '1',
                'nosiritong' => 'A2041531',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
            [
                'skim' => 'PHKT01',
                'jenispremis' => 'RUMAH',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'WAKIL',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 120L',
                'jumlahtong' => '1',
                'nosiritong' => 'A2041531',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
            [
                'skim' => 'PHKT01',
                'jenispremis' => 'RUMAH',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'PENYEWA',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 240L',
                'jumlahtong' => '1',
                'nosiritong' => 'A2041531',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
            [
                'skim' => 'PHKT01',
                'jenispremis' => 'RUMAH',
                'lokasi_nomborpremis_namaprogram' => 'Kampung Belukar Jalan Gambang',
                'namajalan' => 'Jalan Gambar 52',
                'namataman' => 'Kampung Belukar',
                'noposkod' => '25150',
                'negeri' => 'PAHANG',
                'statuspenerima' => 'PENYEWA',
                'namapenerima' => 'Zainab Bin Din',
                'nokadpengenalan_nopassport' => '7302038765',
                'notelefon' => '0187625342',
                'emel' => 'zainab@gmail.com',
                'warganegara' => 'Malaysia',
                'kategoripermohonan' => 'OPERASI',
                'jenistong' => 'MGB 240L',
                'jumlahtong' => '1',
                'nosiritong' => 'A3980223',
                'nosiritonglama' => '',
                'kategoripenerimaantong' => 'VO BARU',
                'catatan' => '',
                'perakuanpenerima' => 'SAYA SETUJU DENGAN SYARAT-SYARAT YANG DINYATAKAN',
                'gambarpenghantarantong' => 'https://drive.google.com/opem?id=ka89ueijnd0jdewoihjewoi',
                'namapekerja' => 'Zikril Hakim',
                'nopekerja' => '97000916',
                'nolori' => 'WXF 6729',
                'penghantarantong' => 'TONG BARU',
            ],
        ];

        for($i=0; $i<count($bins); $i++){
            Bin::create($bins[$i]);
        }
    }
}
